apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: medium-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: medium-example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: medium-customer-manager-service
            servicePort: 80
        - path: /customer
          backend:
            serviceName: customer-medium-customer
            servicePort: 80
